config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  resources :reminders do
    member do
      get :close
      get :print
    end
  end
  resources :reminder_types
  resources :customers do
    member do
      get :print
    end
    resources :reminders do
      member do
        get :close
      end
    end
  end
  devise_for :users
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  enum occurence: [:every_day , :every_week, :every_month, :every_year]
  enum status: [:open, :closed]
  belongs_to :reminder_type
  belongs_to :customer
end

app/models/reminder_type.rb
class ReminderType < ApplicationRecord
    has_many :reminders
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer
  before_action :set_reminder, only: %i[ show edit update destroy close]

  # GET /reminders or /reminders.json
  def index 
    if @customer
      @reminders = @customer.reminders
    else  
      @reminders = Reminder.all
    end
    params[:filter_by] ||= 'today'
    case(params[:filter_by])
    when 'today'
      @reminders = @reminders.where(expiry_date: Date.today)
    when 'week'
      @reminders = @reminders.where(expiry_date: Time.now..(Time.now + 1.week))
    when 'month'
      @reminders = @reminders.where(expiry_date: Date.today..(Date.today + 1.month))
    end
    #@reminders = @reminders.paginate(page: params[:page], per_page: 1)
    @reminders = @reminders.paginate(page: params[:page], per_page: params[:per_page] || 5) 

  end

  # GET /reminders/1 or /reminders/1.json
  def show
  end

  def close
    @reminder.closed!
    # @reminder.status = "close"
    # @reminder.save
    if @customer 
      redirect_to customer_reminders_path(@customer)
    else
      redirect_to reminders_path
    end
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end
  
  def print
    respond_to do |format|
      format.html{render "print",layout: false}
      format.pdf do
        render :pdf => "print",:margin => { :top => 5, :bottom => 5, :left => 10, :right => 4 }, :layout => 'pdf1.html'
      end
    end
  end

  # POST /reminders or /reminders.json
  def create
    if @customer
      @reminder = @customer.reminders.build(reminder_params)
    else
      @reminder = Reminder.new(reminder_params)
    end

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: "Reminder was successfully created." }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1 or /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: "Reminder was successfully updated." }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1 or /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: "Reminder was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_customer
    @customer = Customer.find_by_id(params[:customer_id])
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reminder_params
      params.require(:reminder).permit(:reminder_type_id, :reminder_content, :expiry_date, :occurence, :customer_id )
    end

end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_form.html.erb
<div class="col-md-5">
  <%= form_with(model: params[:customer_id].present? ? [@customer, reminder] : reminder, local: true) do |form| %>
    <% if reminder.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

        <ul>
        <% reminder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :reminder_type_id %>
      <%= form.select :reminder_type_id, ReminderType.all.map{|r| [r.name, r.id]},{prompt: "Select reminder type"}, {class: "form-control"} %>
    </div>

    <div class="field">
      <%= form.label :occurence %>
      <%= form.select :occurence, Reminder.occurences.map{|k,v| [k,v]}.map{|arr| [arr[0].capitalize.gsub('_',' '),arr[0]]},{prompt: "Select "}, {class: "form-control"} %>
    </div>

    <div class="field">
      <%= form.label :reminder_content %>
      <%= form.text_field :reminder_content, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :expiry_date %>
      <%= form.date_select :expiry_date %>
    </div>
    <% unless params[:customer_id].present? %>
      <div class="field">
        <%= form.label :customer_id %>
        <%= form.select :customer_id, Customer.all.map {|c| [c.name, c.id]},{prompt: "Select Customer"}, {class: "form-control"} %>
      </div>
    <% end %>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/reminders/_reminders.html.erb
<table class="table" style="min-height: 500px">
  <thead>
    <tr>
      <th>Reminder type</th>
      <th>Reminder content</th>
      <th>Expiry date</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.reminder_type.name %></td>
        <td><%= reminder.reminder_content %></td>
        <td><%= reminder.expiry_date %></td>
        <td><%= link_to 'Show', reminder , class:"badge rounded-pill bg-info text-dark" %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder), class: "badge rounded-pill bg-success" %></td>
        <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' }, class: "badge rounded-pill bg-danger" %></td>
        <td><%= link_to 'Close', @customer ? close_customer_reminder_path(@customer,reminder) : close_reminder_path(reminder), class: "badge rounded-pill bg-warning" if reminder.open?  %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate reminders, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<%= form_with url: @customer ? customer_reminders_path(@customer, params.permit[:filter_by]) : reminders_path(params.permit[:filter_by]),html: {id: 'paginet', method: :get} do %>
<%= select_tag :per_page,options_for_select([10,20,30],params[:per_page] || 10),{onchange: "this.form.submit()"} %>
<% end %>

app/views/reminders/edit.html.erb
<h3>Editing Reminder</h3>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<h3><%= @customer.name if @customer %> Reminders</h3>
<%= link_to 'New Reminder',params[:customer_id].present? ? new_customer_reminder_path : new_reminder_path %>
<ul class="nav nav-tabs">
  <li class="nav-item ">
    <a class="nav-link text-danger <%= 'active' if params[:filter_by] == 'today' %>" href="<%= @customer ? customer_reminders_path(@customer, filter_by: 'today') : reminders_path(filter_by: 'today') %>">Today</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-warning <%= 'active' if params[:filter_by] == 'week' %>" href="<%= @customer ? customer_reminders_path(@customer, filter_by: 'week' ) : reminders_path(filter_by: 'week') %>"> Week</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-success <%= 'active' if params[:filter_by] == 'month' %>" href="<%= @customer ? customer_reminders_path(@customer, filter_by: 'month') : reminders_path(filter_by: 'month') %>"> Month</a>
  </li>
</ul>
<%= render "reminders", reminders: @reminders %> <br>
<p><%= link_to 'Print', print_reminder_path(@reminder, format: :pdf), class: "badge rounded-pill bg-info", target: "blank" %></p>

app/views/reminders/new.html.erb
<h3>New Reminder</h3>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/print.pdf.erb
<div class="center">
<h2> Welcome to Reminder App </h1>
<h4> We have the following reminders </h4> <br>
<table class="table">
    <thead>
      <tr>
        <th> Reminder </th>
        <th> occurence </th>
    </tr>
    </thead>
    <tbody>
        <tr>
          <td> <%= %> </td>
          <td> <%= %> </td>
        </tr>
    </tbody>
  </table>
  </div>

app/views/reminders/show.html.erb
<p>
  <strong>Reminder type:</strong>
  <%= @reminder.reminder_type.name %>
</p>

<p>
  <strong>Reminder content:</strong>
  <%= @reminder.reminder_content %>
</p>

<p>
  <strong>Expiry date:</strong>
  <%= @reminder.expiry_date %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @reminder.customer.name %>
</p>

<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', reminders_path %>