config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  resources :reminders do
    member do
      get :close
      get :print
    end
  end
  resources :reminder_types
  resources :customers do
    member do
      get :print
    end
    resources :reminders do
      member do
        get :close
      end
    end
  end
  devise_for :users
end

app/controllers/reminder_types_controller.rb
class ReminderTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reminder_type, only: %i[ show edit update destroy ]

  # GET /reminder_types or /reminder_types.json
  def index
    @reminder_types = ReminderType.all
  end

  # GET /reminder_types/1 or /reminder_types/1.json
  def show
  end

  # GET /reminder_types/new
  def new
    @reminder_type = ReminderType.new
  end

  # GET /reminder_types/1/edit
  def edit
  end

  # POST /reminder_types or /reminder_types.json
  def create
    @reminder_type = ReminderType.new(reminder_type_params)

    respond_to do |format|
      if @reminder_type.save
        format.html { redirect_to @reminder_type, notice: "Reminder type was successfully created." }
        format.json { render :show, status: :created, location: @reminder_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reminder_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminder_types/1 or /reminder_types/1.json
  def update
    respond_to do |format|
      if @reminder_type.update(reminder_type_params)
        format.html { redirect_to @reminder_type, notice: "Reminder type was successfully updated." }
        format.json { render :show, status: :ok, location: @reminder_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reminder_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminder_types/1 or /reminder_types/1.json
  def destroy
    @reminder_type.destroy
    respond_to do |format|
      format.html { redirect_to reminder_types_url, notice: "Reminder type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder_type
      @reminder_type = ReminderType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reminder_type_params
      params.require(:reminder_type).permit(:name)
    end
end

app/helpers/reminder_types_helper.rb
module ReminderTypesHelper
end

app/views/reminder_types/_form.html.erb
<div class="col-md-5" >
  <%= form_with(model: reminder_type) do |form| %>
    <% if reminder_type.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(reminder_type.errors.count, "error") %> prohibited this reminder_type from being saved:</h2>

        <ul>
          <% reminder_type.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name , class: "form-control" %>
    </div>
    <br>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  </div>

app/views/reminder_types/edit.html.erb
<h3>Editing Reminder Type</h3>

<%= render 'form', reminder_type: @reminder_type %>

<%= link_to 'Show', @reminder_type %> |
<%= link_to 'Back', reminder_types_path %>

app/views/reminder_types/index.html.erb
<h3>Reminder Types</h3>

<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <th> Actions </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminder_types.each do |reminder_type| %>
      <tr>
        <td><%= reminder_type.name %></td>
        <td><%= link_to 'Show', reminder_type, class: "text-primary" %></td>
        <td><%= link_to 'Edit', edit_reminder_type_path(reminder_type), class: "text-success" %></td>
        <td><%= link_to 'Destroy', reminder_type, method: :delete, data: { confirm: 'Are you sure?'}, class: "text-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder Type', new_reminder_type_path %>

app/views/reminder_types/new.html.erb
<h3>New Reminder Type</h3>

<%= render 'form', reminder_type: @reminder_type %>

<%= link_to 'Back', reminder_types_path %>

app/views/reminder_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @reminder_type.name %>
</p>

<%= link_to 'Edit', edit_reminder_type_path(@reminder_type) %> |
<%= link_to 'Back', reminder_types_path %>