config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  resources :reminders do
    member do
      get :close
      get :print
    end
  end
  resources :reminder_types
  resources :customers do
    member do
      get :print
    end
    resources :reminders do
      member do
        get :close
      end
    end
  end
  devise_for :users
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :reminders
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: %i[ show edit update destroy print ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
    @customers = @customers.paginate(page: params[:page], per_page: params[:per_page] || 5) 
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  def print
    # pdf = WickedPdf.new.pdf_from_string("<h1>Customer name: #{@customer.name}</h1>")
    # send_data pdf, filename: "customer-#{@customer.id}.pdf"
    respond_to do |format|
      format.html{render "print",layout: false}
      format.pdf do
        render :pdf => "print",:margin => { :top => 5, :bottom => 5, :left => 10, :right => 4 }, :layout => 'pdf1.html'
      end
    end
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :phone, :email)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<div class="col-md-5">
  <%= form_with(model: customer) do |form| %>
    <% if customer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

        <ul>
          <% customer.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :phone %>
      <%= form.text_field :phone, class: "form-control"  %>
    </div><br>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control"  %>
    </div><br>

    <div class="actions">
      <%= form.submit class: "form-control" "btn btn-outline-primary" %>
    </div>
  <% end %>
</div>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Customers</h1>


<%= link_to 'Todays Reminders', today_reminders_path(@customer),class: "btn btn-warning" if @customer %> 
<%= link_to 'Upcoming', upcoming_reminders_path(@customer),class: "btn btn-success" if @customer %> 

<%= link_to 'New Customer', new_customer_path , class: "text-success" %>
<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.phone %></td>
        <td><%= link_to 'Reminders', customer_reminders_path(customer) %></td>
        <td><%= link_to 'Show', customer, class: "badge rounded-pill bg-info" %></td>
        <td><%= link_to 'Print', print_customer_path(customer, format: :pdf), class: "badge rounded-pill bg-warning", target: "blank" %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer), class: "badge rounded-pill bg-success"  %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' }, class: "badge rounded-pill bg-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @customers, renderer:  WillPaginate::ActionView::BootstrapLinkRenderer %>
<%= form_with url: customers_path(params.permit[:filter_by]) ,html: {id: 'paginet', method: :get} do %>
<%= select_tag :per_page,options_for_select([2,5,10],params[:per_page] || 5),{onchange: "this.form.submit()"} %>
<% end %>

app/views/customers/new.html.erb
<h3>New Customer</h3>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path , class: "badge bg-secondary" %>

app/views/customers/print.pdf.erb
<div class="row">
  <div class="col-xs-2">
    <%= wicked_pdf_image_tag 'logo.jpg',width: "100px",height: "70px" %>
  </div>
  <div class="col-xs-7">
    <h2 style="font-weight: 700;margin-top: 0px;margin-bottom: 5px;" class="text-center">Reminders App</h2>     
    <p class="text-center" style="font-size: 11pt;margin-bottom: 2px;">Welcome <%= "#{@customer.name}"%>! </b></p>
    <p class="text-center" style="font-size: 11pt;margin-bottom: 2px;">Thanks for choosing us</b></p>
  </div>
  <div class="col-xs-3">
    <p class="pull-right" style="font-size: 10pt;margin-bottom: 0px;"><b>Contact number: <%= @customer.phone %> </b></p> <br>
    <p class="pull-right" style="font-size: 10pt;margin-bottom: 0px;"><b>Email: <%= @customer.email %> </b></p>
  </div>
</div> <br>
<table class="table">
    <thead>
      <tr>
        <th> Reminder </th>
        <th> Reminder date </th>
    </tr>
    </thead>
    <tbody>
        <tr>
          <td> <%= %> </td>
          <td> <%= %> </td>
        </tr>
    </tbody>
  </table>

app/views/customers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer), class: "badge rounded-pill bg-success"  %> |
<%= link_to 'Back', customers_path, class: "badge rounded-pill bg-secondary"  %>