config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  resources :reminders do
    member do
      get :close
      get :print
    end
  end
  resources :reminder_types
  resources :customers do
    member do
      get :print
    end
    resources :reminders do
      member do
        get :close
      end
    end
  end
  devise_for :users
end

app/views/common/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Reminder App</a>
      
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= customers_path %>">Customers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= reminders_path %>"> Reminders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= reminder_types_path %>"> Reminder Types</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= reminder_types_path %>"> Upcoming Reminders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= today_reminders_path %>"> Today</a>
        </li>
      </ul>
      
  </div>
</nav>

app/views/common/_toggle_nav.html.erb
<nav class="navbar navbar-light" style="background-color:lightcyan">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Reminder App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= customers_path %>">Customers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= reminders_path %>"> Reminders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= reminder_types_path %>"> Reminder Types</a>
        </li>
        <li class="nav-item">
        <%= link_to 'Log Out', destroy_user_session_path , method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>